# Generated by Django 5.2.6 on 2025-11-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstralSign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."astral_sign',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."meeting_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."social_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField()),
                ('date_birth', models.DateField()),
                ('adress', models.CharField()),
                ('sex', models.BooleanField()),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('hair_color', models.CharField()),
                ('eye_color', models.CharField()),
                ('educational_level', models.SmallIntegerField()),
                ('children_quantity', models.SmallIntegerField()),
                ('bad_habits', models.CharField()),
                ('astral_sign', models.ForeignKey(db_column='astral_sign', on_delete=django.db.models.deletion.DO_NOTHING, to='main.astralsign')),
                ('social_status', models.ForeignKey(db_column='social_status', on_delete=django.db.models.deletion.DO_NOTHING, to='main.socialstatus')),
            ],
            options={
                'db_table': 'main"."client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField()),
                ('datetime', models.DateTimeField()),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='main.client')),
                ('id_meeting_type', models.ForeignKey(db_column='id_meeting_type', on_delete=django.db.models.deletion.DO_NOTHING, to='main.meetingtype')),
            ],
            options={
                'db_table': 'main"."meeting_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('pk', models.CompositePrimaryKey('sender_id', 'recipient_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('text', models.CharField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_recipient_set', to='main.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.client')),
            ],
            options={
                'db_table': 'main"."message',
                'managed': True,
            },
        ),
    ]
