# Generated by Django 6.0.1 on 2026-01-24 04:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS main;",
            reverse_sql="DROP SCHEMA IF EXISTS main CASCADE;"
        ),
        migrations.CreateModel(
            name='AstralSign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."astral_sign',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."meeting_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."social_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(max_length=120, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('sex', models.CharField(max_length=120, null=True)),
                ('height', models.CharField(max_length=120, null=True)),
                ('weight', models.CharField(max_length=120, null=True)),
                ('hair_color', models.CharField(max_length=120, null=True)),
                ('eye_color', models.CharField(max_length=120, null=True)),
                ('educational_level', models.SmallIntegerField(null=True)),
                ('children_quantity', models.SmallIntegerField(null=True)),
                ('bad_habits', models.CharField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('astral_sign', models.ForeignKey(db_column='astral_sign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.astralsign')),
                ('social_status', models.ForeignKey(db_column='social_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.socialstatus')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField()),
                ('datetime', models.DateTimeField()),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_meeting_type', models.ForeignKey(db_column='id_meeting_type', on_delete=django.db.models.deletion.DO_NOTHING, to='main.meetingtype')),
            ],
            options={
                'db_table': 'main"."meeting_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('pk', models.CompositePrimaryKey('sender_id', 'recipient_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('text', models.CharField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_recipient_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main"."message',
                'managed': True,
            },
        ),
    ]
