# Generated by Django 6.0.1 on 2026-02-28 12:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='public/articles_img/%Y/%m/%d')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AstralSign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField()),
            ],
            options={
                'db_table': 'astral_sign',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField()),
            ],
            options={
                'db_table': 'educational_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_deadline', models.DateTimeField()),
                ('title', models.CharField(null=True)),
                ('place', models.CharField(null=True)),
                ('info', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField()),
            ],
            options={
                'db_table': 'meeting_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(max_length=120, null=True)),
                ('date_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('sex', models.CharField(max_length=120, null=True)),
                ('children_quantity', models.SmallIntegerField(null=True)),
                ('bad_habits', models.CharField(null=True)),
                ('interests', models.CharField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('astral_sign', models.ForeignKey(db_column='astral_sign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.astralsign')),
                ('educational_level', models.ForeignKey(db_column='educational_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.educationallevel')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat',
                'managed': True,
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.event')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(null=True)),
                ('event', models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='main.event')),
                ('user1', models.ManyToManyField(db_column='user1', related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeetingClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField()),
                ('datetime', models.DateTimeField()),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_meeting_type', models.ForeignKey(db_column='id_meeting_type', on_delete=django.db.models.deletion.DO_NOTHING, to='main.meetingtype')),
            ],
            options={
                'db_table': 'meeting_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(db_column='chat', default=' ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='main.chat')),
                ('recipient', models.ForeignKey(db_column='recipient', on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['datetime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.post_image_path)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentaries', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, db_column='parent_comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='main.commentaries')),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='main.post')),
            ],
            options={
                'db_table': 'commentaries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(null=True)),
                ('rated_user', models.ForeignKey(db_column='rated_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(db_column='rater', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Авто')], default='auto', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
