# Generated by Django 6.0.1 on 2026-01-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='public/articles_img/%Y/%m/%d')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
