# Generated by Django 6.0.1 on 2026-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=''),
        ),
    ]
