# Generated by Django 6.0.1 on 2026-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
