# Generated by Django 6.0.1 on 2026-02-02 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_eye_color_remove_user_hair_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField()),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('date_deadline', models.DateField()),
                ('title', models.CharField(max_length=120, null=True)),
                ('place', models.CharField(max_length=120, null=True)),
                ('info', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.event')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
