# Generated by Django 6.0.1 on 2026-02-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_eventuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
