# Generated by Django 6.0.1 on 2026-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_date_begin_alter_event_date_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
