# Generated by Django 5.2.15 on 2026-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_image_remove_user_avatar_post_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принята'), ('declined', 'Отклонена')], default='pending', max_length=20),
        ),
    ]
