# Generated by Django 6.0.1 on 2026-02-03 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_info_alter_event_place_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(null=True)),
                ('rated_user', models.ForeignKey(db_column='rated_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(db_column='rater', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main"."rating',
                'managed': True,
            },
        ),
    ]
