# Generated by Django 6.0.1 on 2026-02-05 04:19

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.post_image_path)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main"."post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, db_column='parent_comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.commentaries')),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='main.post')),
            ],
            options={
                'db_table': 'main"."commentaries',
                'managed': True,
            },
        ),
    ]
