# Generated by Django 6.0.1 on 2026-02-06 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post_commentaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='parent_comment',
            field=models.ForeignKey(blank=True, db_column='parent_comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='main.commentaries'),
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='post',
            field=models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='main.post'),
        ),
    ]
