# Generated by Django 6.0.1 on 2026-02-06 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_commentaries_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_time',
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='pk',
            field=models.CompositePrimaryKey('sender', 'recipient', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(db_column='recipient', on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main"."chat',
                'managed': True,
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(db_column='chat', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='main.chat'),
        ),
    ]
