# Generated by Django 6.0.1 on 2026-02-10 04:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_message_options_remove_message_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(null=True)),
                ('event', models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='main.event')),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main"."meeting',
                'managed': True,
            },
        ),
    ]
