# Generated by Django 6.0.1 on 2026-02-10 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user1',
        ),
        migrations.AddField(
            model_name='meeting',
            name='user1',
            field=models.ManyToManyField(db_column='user1', related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
