# Generated by Django 6.0.1 on 2026-02-10 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_meeting_user1_meeting_user1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'managed': True, 'ordering': ['-datetime']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='user2',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(db_table='main.meeting_participants', related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='main.event'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
