# Generated by Django 6.0.1 on 2026-02-10 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_meeting_options_remove_meeting_user1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='meeting',
            name='user1',
            field=models.ManyToManyField(db_column='user1', related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user2',
            field=models.ForeignKey(db_column='user2', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='main.event'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(null=True),
        ),
    ]
