# Generated by Django 6.0.1 on 2026-02-10 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_meeting_options_remove_meeting_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Авто')], default='auto', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
