# Generated by Django 6.0.1 on 2026-02-11 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField()),
            ],
            options={
                'db_table': 'main"."educational_level',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='social_status',
            field=models.ForeignKey(db_column='social_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.educationallevel'),
        ),
        migrations.DeleteModel(
            name='SocialStatus',
        ),
    ]
