# Generated by Django 6.0.1 on 2026-02-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_educationallevel_alter_user_social_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_level',
            field=models.ForeignKey(db_column='level_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.educationallevel'),
        ),
    ]
