# Generated by Django 6.0.1 on 2026-02-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_user_social_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_level',
            field=models.ForeignKey(db_column='educational_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.educationallevel'),
        ),
    ]
